import React from "react";
import styles from "./Insights.module.css";
import { useSelector, useDispatch } from 'react-redux'
import UploadSection from "./UploadSection";

const Insights = () => {

  let currentDatasetIndex = useSelector((state)=>{
    return state.datasetIndex.index;
  })

  let insights = useSelector((state)=>{
    if(state.data.data.data.length!=0){
      return state.data.data.data[currentDatasetIndex].LLMResult.insights;
    }else{
      return undefined;
    }
  })

  if(insights){
    return (
      <div className={styles.container}>
        {/* Page Header */}
        <div className={styles.header}>
          <h1>AI Business Insights ✨</h1>
          <p>Actionable intelligence generated from your business data</p>
        </div>
  
        {/* Insight Summary Cards */}
  
        <div className={styles.summaryGrid}>
  
          {insights.map((insight,indx)=>{
            return (<div key={indx} className={`${styles.card} ${styles.neutral}`}>
              <h3>{insight.title}</h3>
              <p>{insight.description}</p>
            </div>)
          })}
  
        </div>
  
        {/* Footer */}
        <div className={styles.footer}>
          <p>Insights generated by Intellexa AI Engine</p>
        </div>
      </div>
    );
  }else{
    return <UploadSection />
  }
};

export default Insights;
