import React from "react";
import styles from "./Predictions.module.css";
import { useSelector, useDispatch } from 'react-redux'
import UploadSection from "./UploadSection";

const Predictions = () => {
  
  let currentDatasetIndex = useSelector((state)=>{
    return state.datasetIndex.index;
  })
  let aiRecommendations = useSelector((state)=>{
    if(state.data.data.data.length!=0){
      return state.data.data.data[currentDatasetIndex].LLMResult.aiRecommendation;
    }else{
      return undefined;
    }
  })

  if(aiRecommendations){
    return (
      <div className={styles.container}>
        {/* Header */}
        <div className={styles.header}>
          <h1>AI Recommendations 🔮</h1>
          <p>Recommendations powered by Intellexa AI</p>
        </div>
  
       {/* AI Recommendations */}
  <div className={styles.section}>
  
    {
      aiRecommendations.map((aiRecommendation)=>{
        return (
          <div className={styles.recommendationGrid}>
  
          <div className={styles.recommendCard}>
            <div className={styles.recHeader}>
              <span className={styles.priorityMedium}>Medium Priority</span>
            </div>
            <h4>{aiRecommendation.title}</h4>
            <p>
            {aiRecommendation.description}
            </p>
          </div>
        </div>
        )
      })
    }
  
  </div>
  
  
        {/* Footer */}
        <div className={styles.footer}>
          <p>Predictions generated by Intellexa AI Engine</p>
        </div>
      </div>
    );
  }else{
    return <UploadSection />
  }
};

export default Predictions;
