import React from "react";
import styles from "./Insights.module.css";
import { useSelector, useDispatch } from 'react-redux'
import UploadSection from "./UploadSection";

const RiskAndDetection = () => {

  let currentDatasetIndex = useSelector((state)=>{
    return state.datasetIndex.index;
  })

  let risks = useSelector((state) => {
    if(state.data.data.data.length!=0){
      return state.data.data.data[currentDatasetIndex].LLMResult.risk;
    }else{
      return undefined;
    }
  })
  if(risks){
    return (
      <div className={styles.container}>
        {/* Page Header */}
        <div className={styles.header}>
          <h1>Risk & Anomaly Detection</h1>
          <p>Risk and Anomalies generated from your business data</p>
        </div>
  
        {/* Insight Summary Cards */}
        <div className={styles.summaryGrid}>
          {risks.map((risk) => {
            return (
              <div className={`${styles.card} ${styles.alert}`}>
                <h4>{risk.title}</h4>
                <p>
                  {risk.description}
                </p>
              </div>
            )
          })}
  
        </div>
  
        {/* Footer */}
        <div className={styles.footer}>
          <p>Risk and Anomalies generated by Intellexa AI Engine</p>
        </div>
      </div>
    );
  }else{
    return <UploadSection />
  }
};

export default RiskAndDetection;